[Config]
RedisHealthCheckTimer = 2
HeartBeat = false
HBTimer = 10 
HBTicker = 4
Debug = 1

[Log]
LogDir = "./log/"
LogFileName = ""
LogConfig = "./log.xml"

[ServerApp]
ListenAddr = "127.0.0.1:17011"
OuterIP = "127.0.0.1"
SvrMaxConn = 10000
IsEncrypt = false
Services = "Worker"

[Worker]
SvrListenAddr = "127.0.0.1:18001"
OuterIP="127.0.0.1"
VerifyMsgID = 0
TickInterval = 1000 

[DB]
Addr = "127.0.0.1:6379"
MaxIdle = 50
IdleTimeout = 10
MaxActive = 500
Password = ""
Index = 1

[RedisForServer]
Addr = "127.0.0.1:6379"
MaxIdle = 50
IdleTimeout = 10
MaxActive = 500
Password = ""
Index = 0
