shell:

unity:
 target:
  - v20183
  - v20184
 prefer:
  - android
  - windows
 version:
  v20183: D:\Program Files\UnityVersions\2018.3.5f1\Editor\Unity.exe
  v20184: D:\Program Files\UnityVersions\2018.4.3f1\Editor\Unity.exe

zip:

ftp:
 address: 127.0.0.1:21
 username: username
 password: pwd

email:
 smtp: "smtp.email.server.com"
 port: 465
 auth: true
 username: username
 password: pwd